# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # All Vagrant configuration is done here. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "hashicorp/precise32"
  # config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.provision :shell, path: "setUserConfig.sh"

  config.vm.provision "file", source: ".procmailrc", destination: "~/.procmailrc"
  config.vm.provision "file", source: ".msmtprc", destination: "~/.msmtprc"
  config.vm.provision "file", source: ".muttrc", destination: "~/.muttrc"
  config.vm.provision "file", source: ".fetchmailrc", destination: "~/.fetchmailrc"
  config.vm.provision "file", source: ".bashrc", destination: "~/.bashrc"

  config.vm.provision :shell, path: "install.sh"

end
